### ISSUE TITLE
Rename "cloud.svg" to "Cloud.svg" on server

### ISSUE THREAD

**Issue by theSdev** [meyerweb/csstdg4figs#5]
Chapter 19 samples look for a file named "Cloud.svg" but it's actually named "cloud.svg" on the server which causes failure in file loading.

**Comment by meyerweb** [comment]
Oh, good catch.  Apparently my filesystem isn’t case-sensitive, or else my copy of git isn’t, because when I renamed the SVG file, it said there were no changes to commit.  So I updated the references to it instead.  Thanks!
